version: '3.7'

services:
     iobroker:
          image: buanet/iobroker:v9.1.2@sha256:84f0699976f54fde3a9e321240f94d7d526ba9cc73e3f2f669a8facc6f4da294
          container_name: iobroker
          restart: always
          network_mode: bridge
          privileged: true
          ports:
               - '8097:8081'
          volumes:
               - ${APP_DATA_DIR}/data:/opt/iobroker
               - ${UMBREL_ROOT}/data/storage/downloads:/media
               - /dev:/dev
               - /run/dbus:/run/dbus:ro
          environment:
               - TZ=Europe/Berlin
